from datetime import date

print("=" * 50)
print("  Moral Fabric — Client Report Generator")
print("=" * 50)
print()

name = input("1. What is the client's organization name? ").strip()
challenge = input("2. What is their biggest challenge? ").strip()
team_size = input("3. How many staff members do they have? ").strip()
bookkeeping = input("4. Do they have a bookkeeping system? (yes/no) ").strip().lower()
funder_deadline = input("5. Do they have an upcoming funder deadline? (yes/no) ").strip().lower()

has_bookkeeping = bookkeeping in ("yes", "y")
has_deadline = funder_deadline in ("yes", "y")

urgency = "[HIGH] Funder deadline approaching" if has_deadline else "[STANDARD]"
bookkeeping_status = "[OK] In place" if has_bookkeeping else "[ACTION REQUIRED] Not in place — immediate action required"

today = date.today().strftime("%B %d, %Y")
filename = f"report-{name.lower().replace(' ', '-')}.md"

report = f"""# Client Report — {name}
**Moral Fabric — Internal Document**
*Generated: {today}*

---

## Organization Overview

| Field | Details |
|---|---|
| Organization Name | {name} |
| Team Size | {team_size} staff |
| Report Date | {today} |

---

## Key Findings

**Biggest Challenge:**
> {challenge}

**Bookkeeping System:** {bookkeeping_status}

**Urgency Level:** {urgency}

---

## Recommended Next Steps

{"- **[PRIORITY]** Address funder deadline immediately — ensure financial records are ready for reporting." if has_deadline else "- No immediate funder deadline — use this window to build solid financial foundations."}
{"- Set up a bookkeeping system before any other Finance work begins." if not has_bookkeeping else "- Bookkeeping system is in place — review accuracy and reporting workflows."}
- Schedule a full operational health check using the NGO Health Check tool.
- Assign a Moral Fabric ops lead and confirm the service agreement is signed.

---

*Generated by Moral Fabric Client Report Generator*
"""

with open(filename, "w", encoding="utf-8") as f:
    f.write(report)

print()
print(f"Report saved as: {filename}")
